services:
  - type: web
    name: pdfcast-app
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: podcast-storage
      mountPath: /public/podcasts
      sizeGB: 1
