services:
  - type: web
    name: ai-podcast-generator
    env: node
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libleptonica-dev poppler-utils ffmpeg
      npm install && npm run build
      cd frontend && npm install && npm run build && cd ..
    startCommand: cd backend && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPLOADS_DIR
        value: /data/uploads
      - key: TEMP_DIR
        value: /data/temp
      - key: OUTPUT_DIR
        value: /data/podcasts
      - key: GROQ_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
