services:
  - type: web
    name: pdfcast-app
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: GROQ_API_KEY
        sync: false
    disk:
      name: podcast-storage
      mountPath: /opt/render/project/src/public/podcasts
      sizeGB: 1
